name: Release Notes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ dev ]
    types:
    - labeled
    - unlabeled
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
