name: Release
on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.7.x

      - name: Install Dependencies
        run: npm ci

      - name: Correct Code
        run: npm run test:fix

      - name: Format Code
        run: npm run format
        
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "style: 🎨 format code"
