name: Start Ch1llBlox
on: 
- workflow_dispatch # When you activate the workflow. 
- push # When the repository gets an update.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16.8.x

      - name: Install Npm
        uses: bahmutov/npm-install@v1

      - name: Run Clean Up
        uses: peter-evans/repository-dispatch@v1
        with:
          event-type: clean
          token: ${{ secrets.GIT_TOKEN }}

      - name: Start Bot
        run: npm run start:dev
        env: 
          ADMINS: ${{ secrets.ADMINS }}
          BASEURL: ${{ secrets.BASEURL }}
          BOTLISTTOKEN: ${{ secrets.BOTLISTTOKEN }}
          BOT_INVITE: ${{ secrets.BOT_INVITE }}
          CHAT_BID: ${{ secrets.CHAT_BID }}
          CHAT_KEY: ${{ secrets.CHAT_KEY }}
          DBLKEY: ${{ secrets.DBLKEY }}
          GUILDBLACKLIST: ${{ secrets.GUILDBLACKLIST }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          MONGOOSEURL: ${{ secrets.MONGOOSEURL }}
          OWNERID: ${{ secrets.OWNERID }}
          PREFIX: ${{ secrets.PREFIX }}
          ROBLOXCOOKIE: ${{ secrets.ROBLOXCOOKIE }}
          SENTRYTOKEN: ${{ secrets.SENTRYTOKEN }}
          STATCORDAPIKEY: ${{ secrets.STATCORDAPIKEY }}
          TOKEN: ${{ secrets.TOKEN }}
          USERBLACKLIST: ${{ secrets.USERBLACKLIST }}
          VOTINGPASS: ${{ secrets.VOTINGPASS }}
