name: Start Ch1llBlox
on: 
- workflow_dispatch # When you activate the workflow. 
# - push # When the repository gets an update.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16.8.x

      - name: Install Npm
        uses: bahmutov/npm-install@v1

      - name: Run Clean Up
        uses: peter-evans/repository-dispatch@v1
        with:
          event-type: clean
          token: ${{ secrets.TOKEN }}

      - name: Start Bot
        run: npm run start:dev
